# Generated by Django 3.2.5 on 2022-04-12 06:48

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20220410_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.CharField(max_length=1000000, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
